# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lda.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lda.proto',
  package='lda',
  serialized_pb='\n\tlda.proto\x12\x03lda\"!\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05topic\x18\x02 \x01(\x05\"&\n\nDocumentPB\x12\x18\n\x05words\x18\x01 \x03(\x0b\x32\t.lda.Word\"\'\n\x07NonZero\x12\r\n\x05topic\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"7\n\x14SparseTopicHistogram\x12\x1f\n\tnon_zeros\x18\x01 \x03(\x0b\x32\x0c.lda.NonZero\"X\n\x12WordTopicHistogram\x12\x0c\n\x04word\x18\x01 \x01(\x05\x12\x34\n\x11sparse_topic_hist\x18\x02 \x01(\x0b\x32\x19.lda.SparseTopicHistogram\",\n\x14GlobalTopicHistogram\x12\x14\n\x0ctopic_counts\x18\x01 \x03(\x03\"6\n\x0bHyperParams\x12\x13\n\x0btopic_prior\x18\x01 \x01(\x01\x12\x12\n\nword_prior\x18\x02 \x01(\x01')




_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='lda.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lda.Word.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='lda.Word.topic', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=51,
)


_DOCUMENTPB = _descriptor.Descriptor(
  name='DocumentPB',
  full_name='lda.DocumentPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='lda.DocumentPB.words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=91,
)


_NONZERO = _descriptor.Descriptor(
  name='NonZero',
  full_name='lda.NonZero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='lda.NonZero.topic', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='lda.NonZero.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=132,
)


_SPARSETOPICHISTOGRAM = _descriptor.Descriptor(
  name='SparseTopicHistogram',
  full_name='lda.SparseTopicHistogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='non_zeros', full_name='lda.SparseTopicHistogram.non_zeros', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=189,
)


_WORDTOPICHISTOGRAM = _descriptor.Descriptor(
  name='WordTopicHistogram',
  full_name='lda.WordTopicHistogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='lda.WordTopicHistogram.word', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparse_topic_hist', full_name='lda.WordTopicHistogram.sparse_topic_hist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=191,
  serialized_end=279,
)


_GLOBALTOPICHISTOGRAM = _descriptor.Descriptor(
  name='GlobalTopicHistogram',
  full_name='lda.GlobalTopicHistogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_counts', full_name='lda.GlobalTopicHistogram.topic_counts', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=325,
)


_HYPERPARAMS = _descriptor.Descriptor(
  name='HyperParams',
  full_name='lda.HyperParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_prior', full_name='lda.HyperParams.topic_prior', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word_prior', full_name='lda.HyperParams.word_prior', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=381,
)

_DOCUMENTPB.fields_by_name['words'].message_type = _WORD
_SPARSETOPICHISTOGRAM.fields_by_name['non_zeros'].message_type = _NONZERO
_WORDTOPICHISTOGRAM.fields_by_name['sparse_topic_hist'].message_type = _SPARSETOPICHISTOGRAM
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['DocumentPB'] = _DOCUMENTPB
DESCRIPTOR.message_types_by_name['NonZero'] = _NONZERO
DESCRIPTOR.message_types_by_name['SparseTopicHistogram'] = _SPARSETOPICHISTOGRAM
DESCRIPTOR.message_types_by_name['WordTopicHistogram'] = _WORDTOPICHISTOGRAM
DESCRIPTOR.message_types_by_name['GlobalTopicHistogram'] = _GLOBALTOPICHISTOGRAM
DESCRIPTOR.message_types_by_name['HyperParams'] = _HYPERPARAMS

class Word(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORD

  # @@protoc_insertion_point(class_scope:lda.Word)

class DocumentPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTPB

  # @@protoc_insertion_point(class_scope:lda.DocumentPB)

class NonZero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NONZERO

  # @@protoc_insertion_point(class_scope:lda.NonZero)

class SparseTopicHistogram(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPARSETOPICHISTOGRAM

  # @@protoc_insertion_point(class_scope:lda.SparseTopicHistogram)

class WordTopicHistogram(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORDTOPICHISTOGRAM

  # @@protoc_insertion_point(class_scope:lda.WordTopicHistogram)

class GlobalTopicHistogram(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GLOBALTOPICHISTOGRAM

  # @@protoc_insertion_point(class_scope:lda.GlobalTopicHistogram)

class HyperParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPERPARAMS

  # @@protoc_insertion_point(class_scope:lda.HyperParams)


# @@protoc_insertion_point(module_scope)
